import { MD3LightTheme, configureFonts } from 'react-native-paper';

const fontConfig = {
  displayLarge: {
    fontFamily: 'System',
    fontSize: 57,
    fontWeight: '400' as const,
    lineHeight: 64,
    letterSpacing: 0,
  },
  displayMedium: {
    fontFamily: 'System',
    fontSize: 45,
    fontWeight: '400' as const,
    lineHeight: 52,
    letterSpacing: 0,
  },
  displaySmall: {
    fontFamily: 'System',
    fontSize: 36,
    fontWeight: '400' as const,
    lineHeight: 44,
    letterSpacing: 0,
  },
  headlineLarge: {
    fontFamily: 'System',
    fontSize: 32,
    fontWeight: '400' as const,
    lineHeight: 40,
    letterSpacing: 0,
  },
  headlineMedium: {
    fontFamily: 'System',
    fontSize: 28,
    fontWeight: '400' as const,
    lineHeight: 36,
    letterSpacing: 0,
  },
  headlineSmall: {
    fontFamily: 'System',
    fontSize: 24,
    fontWeight: '400' as const,
    lineHeight: 32,
    letterSpacing: 0,
  },
  titleLarge: {
    fontFamily: 'System',
    fontSize: 22,
    fontWeight: '500' as const,
    lineHeight: 28,
    letterSpacing: 0,
  },
  titleMedium: {
    fontFamily: 'System',
    fontSize: 16,
    fontWeight: '500' as const,
    lineHeight: 24,
    letterSpacing: 0.15,
  },
  titleSmall: {
    fontFamily: 'System',
    fontSize: 14,
    fontWeight: '500' as const,
    lineHeight: 20,
    letterSpacing: 0.1,
  },
  labelLarge: {
    fontFamily: 'System',
    fontSize: 14,
    fontWeight: '500' as const,
    lineHeight: 20,
    letterSpacing: 0.1,
  },
  labelMedium: {
    fontFamily: 'System',
    fontSize: 12,
    fontWeight: '500' as const,
    lineHeight: 16,
    letterSpacing: 0.5,
  },
  labelSmall: {
    fontFamily: 'System',
    fontSize: 11,
    fontWeight: '500' as const,
    lineHeight: 16,
    letterSpacing: 0.5,
  },
  bodyLarge: {
    fontFamily: 'System',
    fontSize: 16,
    fontWeight: '400' as const,
    lineHeight: 24,
    letterSpacing: 0.15,
  },
  bodyMedium: {
    fontFamily: 'System',
    fontSize: 14,
    fontWeight: '400' as const,
    lineHeight: 20,
    letterSpacing: 0.25,
  },
  bodySmall: {
    fontFamily: 'System',
    fontSize: 12,
    fontWeight: '400' as const,
    lineHeight: 16,
    letterSpacing: 0.4,
  },
};

export const theme = {
  ...MD3LightTheme,
  fonts: configureFonts({ config: fontConfig }),
  colors: {
    ...MD3LightTheme.colors,
    primary: '#6366f1',
    primaryContainer: '#e0e7ff',
    secondary: '#8b5cf6',
    secondaryContainer: '#f3e8ff',
    tertiary: '#ec4899',
    tertiaryContainer: '#fce7f3',
    surface: '#ffffff',
    surfaceVariant: '#f8fafc',
    background: '#f8fafc',
    error: '#ef4444',
    errorContainer: '#fef2f2',
    success: '#10b981',
    warning: '#f59e0b',
    onPrimary: '#ffffff',
    onPrimaryContainer: '#1e1b4b',
    onSecondary: '#ffffff',
    onSecondaryContainer: '#2d1b69',
    onTertiary: '#ffffff',
    onTertiaryContainer: '#4c0d3d',
    onSurface: '#0f172a',
    onSurfaceVariant: '#475569',
    onError: '#ffffff',
    onErrorContainer: '#7f1d1d',
    outline: '#cbd5e1',
    outlineVariant: '#e2e8f0',
    inverseSurface: '#0f172a',
    inverseOnSurface: '#f1f5f9',
    inversePrimary: '#a5b4fc',
    shadow: '#000000',
    scrim: '#000000',
    backdrop: 'rgba(15, 23, 42, 0.5)',
  },
};

export const gradients = {
  primary: ['#6366f1', '#8b5cf6'] as const,
  secondary: ['#8b5cf6', '#ec4899'] as const,
  success: ['#10b981', '#34d399'] as const,
  warning: ['#f59e0b', '#fbbf24'] as const,
  error: ['#ef4444', '#f87171'] as const,
  background: ['#f8fafc', '#f1f5f9'] as const,
  card: ['#ffffff', '#f8fafc'] as const,
};

export type Theme = typeof theme;
export type Gradients = typeof gradients;